name: smb_connect
description: "A new Flutter package project."
version: 0.0.3
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  asn1lib: ^1.5.2
  charset: ^2.0.1
  crypto: ^3.0.3
  cryptography: ^2.7.0
  mutex: ^3.1.0
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
